### ISSUE TITLE
Adding a Dockerfile to this project

### ISSUE THREAD

**Issue by goncalossilva** [kentonv/kvmonitor#2]
First of all, I love that this exists, thank you for building it! I look forward to running this myself soon.

I've taken a jab at creating a Dockerfile for this project, but I'm currently a stuck on linker errors I can't easily figure out. It's been a long while since I've done any C/C++ and I didn't know about capnproto until a few minutes ago, so I'm very likely building it incorrectly.

Linker errors are all `undefined reference` related to capnproto. They show up on the third step, after installing dependencies and building capnproto, where I try to build kvmonitor (right before `# Run kvmonitor`):

```dockerfile
# Build capnproto and kvmonitor
FROM debian:12-slim AS builder
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
    clang++-14 \
    make \
    cmake \
    libcapnp-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libswresample-dev \
    libavutil-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    && update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-14 100

WORKDIR /tmp/capnproto
RUN git clone -b v2 --depth 1 --single-branch https://github.com/capnproto/capnproto.git && \
    cd capnproto/c++ && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=OFF \
          -DBUILD_TESTING=OFF \
          .. && \
    make -j$(nproc) && \
    make install && \
    ldconfig && \
    cd / && \
    rm -rf /tmp/capnproto

WORKDIR /app
#RUN git clone --depth 1 --single-branch https://github.com/kentonv/kvmonitor.git . && \
RUN git clone -b new-async-write-api --depth 1 --single-branch https://github.com/goncalossilva/kvmonitor.git . && \
    make && \
    rm -rf .git

# Run kvmonitor
FROM gcr.io/distroless/static-debian12

WORKDIR /app
COPY --from=builder /app/server /app/server

EXPOSE 58666
ENV CAMERA_URLS=""
CMD /app/server "127.0.0.1:58666" $CAMERA_URLS
```

Please disregard the Dockerfile structure itself. As I tried to figure this out, I've changed a few things.

Perhaps you can share a pointer or two about how to best build capnproto v2 and kvmonitor?

**Comment by kentonv** [comment]
So, I actually don't know much about the cmake build. I never learned cmake myself, and the cmake files were contributed by third parties. I always use the autotools build because although autotools is a mess, I actually wrote that build and intimately understand how it works.

It's been a few months since I touched kvmonitor but I'm pretty sure what I did was install capnproto using the autotools build like:

```
git clone -b v2 https://github.com/capnproto/capnproto.git
cd capnproto/c++
autoreconf -i
./configure
make -j$(nproc) check
sudo make install
```

This installs both static and dynamic libraries. It looks like my makefile is designed to link statically, so that I could build a binary that I could copy to other machines where capnp wasn't necessarily installed. I'd guess the problem you're having with cmake is that it isn't building/installing those static libraries or they don't work the same way somehow.

**Comment by goncalossilva** [comment]
Ah, that makes sense and nudged me in the right direction!

```Dockerfile
FROM debian:12-slim

# Compile and install capnproto
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
    autoconf \
    automake \
    libtool \
    make \
    clang-14 \
    clang++-14 \
    && update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 100 \
    && update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-14 100 \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean
WORKDIR /tmp/capnproto
RUN git clone -b v2 --depth 1 --single-branch https://github.com/capnproto/capnproto.git && \
    cd capnproto/c++ && \
    autoreconf -i && \
    ./configure && \
    make -j$(nproc) && \
    make install && \
    cd ../.. && \
    rm -rf capnprotoµ

# Compile kvmonitor
RUN apt-get update && apt-get install -y --no-install-recommends \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean
WORKDIR /app
RUN git clone --depth 1 --single-branch https://github.com/kentonv/kvmonitor.git && \
    cd kvmonitor && \
    make && \
    cp server .. && \
    cd .. && \
    rm -rf kvmonitor

# Run kvmonitor
WORKDIR /app
EXPOSE 58666
ENV CAMERA_URLS=""
SHELL ["/bin/bash", "-c"]
CMD /app/server "0.0.0.0:58666" $CAMERA_URLS
```

Still not the most elegant Dockerfile, but everything builds and appears to run well. I'll put this through its paces next. 

Would you be interested in a contribution of the Dockerfile, plus a GitHub Action that rebuilds it whenever any of the other files change, or would you prefer this lived elsewhere to avoid bloating the repo?
